fix "Property 'extensions' is missing in type"
tsc error was:

src/queries/queryIntel.ts:250:5 - error TS2345: Argument of type '{ name: string; type: GraphQLInputType; }' is not assignable to parameter of type 'GraphQLInputField'.
  Property 'extensions' is missing in type '{ name: string; type: GraphQLInputType; }' but required in type 'GraphQLInputField'.

250     {
        ~
251       name: node.variable.name.value,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
252       type: getInputType(node, schema)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
253     },
    ~~~~~

  node_modules/graphql/type/definition.d.ts:800:3
    800   extensions: Maybe<Readonly<Record<string, any>>>;
          ~~~~~~~~~~
    'extensions' is declared here.